repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # versión a usar
    hooks:
      - id: prettier
        args: [--write]
        # Sólo formatear este tipos de archivo
        files: \.(js|jsx|ts|tsx|css|scss|html|json|md|ya?ml)$
