version: 0.1
component: build
timeoutInSeconds: 7200  
shell: bash
failImmediatelyOnError: true

steps:
  - type: Command
    name: Build JAR in Maven container
    timeoutInSeconds: 4000    
    command: |
      docker run --rm \
        -v $(pwd)/MtdrSpring/backend:/workspace \
        -w /workspace \
        maven:3.8.7-openjdk-11 \
        mvn clean package spring-boot:repackage -DskipTests
      
  - type: Command
    name: Build and Push Docker Image
    timeoutInSeconds: 7500  
    command: |
      cd MtdrSpring/backend

      docker build -f Dockerfile \
        -t mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag} \
        .
        
      docker push mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag}
