version: 0.1
component: build
timeoutInSeconds: 7200
shell: bash
failImmediatelyOnError: true

steps:
  - type: Command
    name: Prepare JDK 11
    timeoutInSeconds: 600
    command: |
      yum install -y java-11-openjdk-devel

      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      alternatives --set java $JAVA_HOME/bin/java
      alternatives --set javac $JAVA_HOME/bin/javac
      export PATH=$JAVA_HOME/bin:$PATH

  - type: Command
    name: Build and Push Docker Image
    timeoutInSeconds: 3600
    command: |
      cd MtdrSpring/backend
      mvn clean package spring-boot:repackage -DskipTests
      docker build -f Dockerfile \
        -t mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag} .
      docker push mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag}
