version: 0.1
component: build
timeoutInSeconds: 7200
failImmediatelyOnError: true
steps:
  - type: Command
    name: Compile backend
    command: |
      cd MtdrSpring/backend
      mvn clean package spring-boot:repackage
