version: 0.1
component: build
timeoutInSeconds: 7200
shell: bash
failImmediatelyOnError: true

steps:
  - type: Command
    name: Prepare JDK 11
    timeoutInSeconds: 600
    command: |
      # Instala Java 11
      yum install -y java-11-openjdk-devel

  - type: Command
    name: Build and Push Docker Image
    timeoutInSeconds: 3600
    command: |
      # 1) Apunta a tu módulo
      cd MtdrSpring/backend

      # 2) Fuerza que use el JDK 11
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      export PATH=$JAVA_HOME/bin:$PATH

      # 3) Empaquetar con Maven (sin tests para ir rápido)
      mvn clean package spring-boot:repackage -DskipTests

      # 4) Construir y subir la imagen
      docker build -f Dockerfile \
        -t mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag} \
        .
      docker push mx-queretaro-1.ocir.io/axvteqzybmr1/deploy22_repo:${imageTag}
