-- Database setup script for TodoList application
-- This script creates the necessary tables and inserts test data

-- Create EQUIPO table
CREATE TABLE TODOUSER.EQUIPO (
    ID_EQUIPO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR2(100) NOT NULL
);

-- Create DEVELOPER table 
CREATE TABLE TODOUSER.DEVELOPER (
    ID_DEVELOPER NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100) NOT NULL,
    ID_EQUIPO NUMBER NOT NULL,
    ES_MANAGER NUMBER(1) DEFAULT 0,
    TELEFONO VARCHAR2(10),
    CONTRASENA VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_DEVELOPER_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES TODOUSER.EQUIPO(ID_EQUIPO)
);

-- Create SPRINT table
CREATE TABLE TODOUSER.SPRINT (
    ID_SPRINT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

-- Create TAREA table
CREATE TABLE TODOUSER.TAREA (
    ID_TAREA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TAREA VARCHAR2(200) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    HORAS_ESTIMADAS NUMBER(5,2) NOT NULL,
    HORAS_REALES NUMBER(5,2),
    ID_SPRINT NUMBER NOT NULL,
    CONSTRAINT FK_TAREA_SPRINT FOREIGN KEY (ID_SPRINT) REFERENCES TODOUSER.SPRINT(ID_SPRINT)
);

-- Create ESTADO table
CREATE TABLE TODOUSER.ESTADO (
    ID_TAREA NUMBER PRIMARY KEY,
    ESTADO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_ESTADO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TODOUSER.TAREA(ID_TAREA)
);

-- Create PRIORIDAD table
CREATE TABLE TODOUSER.PRIORIDAD (
    ID_TAREA NUMBER PRIMARY KEY,
    PRIORIDAD VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_PRIORIDAD_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TODOUSER.TAREA(ID_TAREA)
);

-- Create MANAGER table (junction table for developers and teams)
CREATE TABLE TODOUSER.MANAGER (
    ID_DEVELOPER NUMBER,
    ID_EQUIPO NUMBER,
    PRIMARY KEY (ID_DEVELOPER, ID_EQUIPO),
    CONSTRAINT FK_MANAGER_DEVELOPER FOREIGN KEY (ID_DEVELOPER) REFERENCES TODOUSER.DEVELOPER(ID_DEVELOPER),
    CONSTRAINT FK_MANAGER_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES TODOUSER.EQUIPO(ID_EQUIPO)
);

-- Create TAREA_DEVELOPER table (junction table for tasks and developers)
CREATE TABLE TODOUSER.TAREA_DEVELOPER (
    ID_TAREA NUMBER,
    ID_DEVELOPER NUMBER,
    PRIMARY KEY (ID_TAREA, ID_DEVELOPER),
    CONSTRAINT FK_TD_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TODOUSER.TAREA(ID_TAREA),
    CONSTRAINT FK_TD_DEVELOPER FOREIGN KEY (ID_DEVELOPER) REFERENCES TODOUSER.DEVELOPER(ID_DEVELOPER)
);

-- Insert test data
-- Insert test teams
INSERT INTO TODOUSER.EQUIPO (NOMBRE_EQUIPO) VALUES ('Desarrollo Backend');
INSERT INTO TODOUSER.EQUIPO (NOMBRE_EQUIPO) VALUES ('Desarrollo Frontend');
INSERT INTO TODOUSER.EQUIPO (NOMBRE_EQUIPO) VALUES ('QA Testing');

-- Insert test developers with phone and password for login
INSERT INTO TODOUSER.DEVELOPER (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_EQUIPO, ES_MANAGER, TELEFONO, CONTRASENA) 
VALUES ('Juan', 'García', 'López', 1, 1, '3121539670', 'contrasenaSegura1');

INSERT INTO TODOUSER.DEVELOPER (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_EQUIPO, ES_MANAGER, TELEFONO, CONTRASENA) 
VALUES ('María', 'Rodríguez', 'Martínez', 1, 0, '4776467654', 'contrasenaSegura4');

INSERT INTO TODOUSER.DEVELOPER (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_EQUIPO, ES_MANAGER, TELEFONO, CONTRASENA) 
VALUES ('Carlos', 'Hernández', 'Pérez', 2, 0, '5551234567', 'password123');

INSERT INTO TODOUSER.DEVELOPER (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_EQUIPO, ES_MANAGER, TELEFONO, CONTRASENA) 
VALUES ('Ana', 'López', 'González', 3, 1, '5559876543', 'secure456');

-- Insert test sprints
INSERT INTO TODOUSER.SPRINT (NOMBRE, FECHA_INICIO, FECHA_FIN) 
VALUES ('Sprint 1', DATE '2024-01-01', DATE '2024-01-15');

INSERT INTO TODOUSER.SPRINT (NOMBRE, FECHA_INICIO, FECHA_FIN) 
VALUES ('Sprint 2', DATE '2024-01-16', DATE '2024-01-30');

-- Insert test tasks
INSERT INTO TODOUSER.TAREA (NOMBRE_TAREA, FECHA_REGISTRO, FECHA_FIN, HORAS_ESTIMADAS, HORAS_REALES, ID_SPRINT) 
VALUES ('Implementar login de usuarios', DATE '2024-01-02', DATE '2024-01-05', 8.0, 6.5, 1);

INSERT INTO TODOUSER.TAREA (NOMBRE_TAREA, FECHA_REGISTRO, FECHA_FIN, HORAS_ESTIMADAS, HORAS_REALES, ID_SPRINT) 
VALUES ('Crear API REST para tareas', DATE '2024-01-03', DATE '2024-01-08', 16.0, 14.0, 1);

INSERT INTO TODOUSER.TAREA (NOMBRE_TAREA, FECHA_REGISTRO, FECHA_FIN, HORAS_ESTIMADAS, HORAS_REALES, ID_SPRINT) 
VALUES ('Diseñar interfaz de usuario', DATE '2024-01-17', DATE '2024-01-25', 20.0, NULL, 2);

-- Insert task states
INSERT INTO TODOUSER.ESTADO (ID_TAREA, ESTADO) VALUES (1, 'Completado');
INSERT INTO TODOUSER.ESTADO (ID_TAREA, ESTADO) VALUES (2, 'En Progreso');
INSERT INTO TODOUSER.ESTADO (ID_TAREA, ESTADO) VALUES (3, 'Pendiente');

-- Insert task priorities
INSERT INTO TODOUSER.PRIORIDAD (ID_TAREA, PRIORIDAD) VALUES (1, 'Alta');
INSERT INTO TODOUSER.PRIORIDAD (ID_TAREA, PRIORIDAD) VALUES (2, 'Normal');
INSERT INTO TODOUSER.PRIORIDAD (ID_TAREA, PRIORIDAD) VALUES (3, 'Urgente');

-- Insert manager assignments
INSERT INTO TODOUSER.MANAGER (ID_DEVELOPER, ID_EQUIPO) VALUES (1, 1);
INSERT INTO TODOUSER.MANAGER (ID_DEVELOPER, ID_EQUIPO) VALUES (4, 3);

-- Insert task-developer assignments
INSERT INTO TODOUSER.TAREA_DEVELOPER (ID_TAREA, ID_DEVELOPER) VALUES (1, 1);
INSERT INTO TODOUSER.TAREA_DEVELOPER (ID_TAREA, ID_DEVELOPER) VALUES (1, 2);
INSERT INTO TODOUSER.TAREA_DEVELOPER (ID_TAREA, ID_DEVELOPER) VALUES (2, 2);
INSERT INTO TODOUSER.TAREA_DEVELOPER (ID_TAREA, ID_DEVELOPER) VALUES (3, 3);

COMMIT;

-- Verify the data
SELECT 'DEVELOPER' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM TODOUSER.DEVELOPER
UNION ALL
SELECT 'EQUIPO', COUNT(*) FROM TODOUSER.EQUIPO
UNION ALL
SELECT 'SPRINT', COUNT(*) FROM TODOUSER.SPRINT
UNION ALL
SELECT 'TAREA', COUNT(*) FROM TODOUSER.TAREA
UNION ALL  
SELECT 'ESTADO', COUNT(*) FROM TODOUSER.ESTADO
UNION ALL
SELECT 'PRIORIDAD', COUNT(*) FROM TODOUSER.PRIORIDAD
UNION ALL
SELECT 'MANAGER', COUNT(*) FROM TODOUSER.MANAGER
UNION ALL
SELECT 'TAREA_DEVELOPER', COUNT(*) FROM TODOUSER.TAREA_DEVELOPER;

-- Show test login credentials
SELECT 'Test Login Credentials:' as INFO FROM DUAL
UNION ALL
SELECT 'Phone: 3121539670, Password: contrasenaSegura1 (Juan García - Manager)' FROM DUAL
UNION ALL
SELECT 'Phone: 4776467654, Password: contrasenaSegura4 (María Rodríguez)' FROM DUAL
UNION ALL
SELECT 'Phone: 5551234567, Password: password123 (Carlos Hernández)' FROM DUAL
UNION ALL
SELECT 'Phone: 5559876543, Password: secure456 (Ana López - Manager)' FROM DUAL;
