apiVersion: apps/v1
kind: Deployment
metadata:
  name: team22-agile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team22-agile-app
  template:
    metadata:
      labels:
        app: team22-agile-app
        version: v1
    spec:
      containers:
        - name: agile-container
          image: ${IMAGE_FULL_NAME}
          imagePullPolicy: Always
          env:
            - name: db_user
              value: "TODOUSER"
            - name: db_url
              value: "jdbc:oracle:thin:@${TODO_PDB_NAME}_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "${REGION}"
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: team22-dbuser
                  key: dbpassword
                  optional: true
            - name: ui_username
              value: "${UI_USERNAME}"
            - name: ui_password
              valueFrom:
                secretKeyRef:
                  name: team22-frontendadmin
                  key: password
                  optional: true
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
      restartPolicy: Always
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: creds
          secret:
            secretName: team22-db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname 
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: team22-agile-app

---
apiVersion: v1
kind: Service
metadata:
  name: team22-agile-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  selector:
    app: team22-agile-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
