spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    # password: PeterSong123
    password: WELcome__12345
    # url: jdbc:oracle:thin:@petertestdb_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_petertestDB
    ## url: jdbc:oracle:thin:@reacttodoia9ge_tp?TNS_ADMIN=C:/Users/diego/OneDrive/Escritorio/wallet
    url: jdbc:oracle:thin:@reacttodoia9ge_tp?TNS_ADMIN=/tmp/wallet
    # username: TODOUSER
    username: TODOUSER
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}