spring:
  datasource:
    driver_class_name: ${driver_class_name:oracle.jdbc.OracleDriver}
    password: ${dbpassword:WELcome__12345}
    url: ${db_url:jdbc:oracle:thin:@reacttodoia9ge_tp?TNS_ADMIN=/tmp/wallet}
    username: ${db_user:TODOUSER}
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}