apiVersion: v1
kind: Service
metadata:
  name: agile-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  # Remove hardcoded IP - let OCI assign dynamically
  externalTrafficPolicy: Cluster

  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: agile-app
---
#this is new stuff for hosting on the load balancer
apiVersion: v1
kind: Service
metadata:
  name: agile-backend-router
spec:
  selector:
    app: agile-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agile-deployment
spec:
  selector:
    matchLabels:
      app: agile-app
  replicas: 2
  template:
    metadata:
      labels:
        app: agile-app
        version: v1
    spec:
      containers:
        - name: agile-container
          image: "%DOCKER_REGISTRY%/todolistapp-springboot:0.1"
          imagePullPolicy: Always
          env:
            - name: db_user
              value: "TODOUSER"
            - name: db_url
              value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "%OCI_REGION%"
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true
            - name: ui_username
              value: "%UI_USERNAME%"
            - name: ui_password
              valueFrom:
                secretKeyRef:
                  name: frontendadmin
                  key: password
                  optional: true
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname 
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: agile-app
---